// Auto-generated by scripts/asset-index.ts - DO NOT EDIT MANUALLY
export type BrandAsset = {
  path: string;
  width: number;
  height: number;
  kind: "favicon" | "icon" | "og" | "social" | "hero";
};

export const BRAND_ASSETS: Record<string, BrandAsset> = {
  "modern_ledger_1024x1024.png": {"path":"/modern_ledger_1024x1024.png","width":1024,"height":1024,"kind":"icon"},
  "modern_ledger_1080x1080.png": {"path":"/modern_ledger_1080x1080.png","width":1080,"height":1080,"kind":"social"},
  "modern_ledger_1200x630.png": {"path":"/modern_ledger_1200x630.png","width":1200,"height":630,"kind":"og"},
  "modern_ledger_128x128.png": {"path":"/modern_ledger_128x128.png","width":128,"height":128,"kind":"icon"},
  "modern_ledger_1920x1080.png": {"path":"/modern_ledger_1920x1080.png","width":1920,"height":1080,"kind":"hero"},
  "modern_ledger_256x256.png": {"path":"/modern_ledger_256x256.png","width":256,"height":256,"kind":"icon"},
  "modern_ledger_32x32.png": {"path":"/modern_ledger_32x32.png","width":32,"height":32,"kind":"favicon"},
  "modern_ledger_512x512.png": {"path":"/modern_ledger_512x512.png","width":512,"height":512,"kind":"icon"},
  "modern_ledger_64x64.png": {"path":"/modern_ledger_64x64.png","width":64,"height":64,"kind":"favicon"}
};
